name: Test Pull Request
on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ feature/*, bugfix/*, hotfix/* ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm install
        
      - name: Run tests
        run: npm run test:run
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-pr-${{ github.event.number }}
          path: |
            coverage/
            test-results.xml
          retention-days: 30
          
      - name: Comment PR with test results
        uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        with:
          script: |
            const { execSync } = require('child_process');
            
            // Run tests again to get output for comment
            try {
              const testOutput = execSync('npm run test:run 2>&1', { encoding: 'utf8' });
              const testPassed = !testOutput.includes('FAILED');
              
              const comment = testPassed 
                ? '✅ **All tests passed!** Ready for merge.'
                : '❌ **Tests failed.** Please fix failing tests before merging.';
                
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: comment + '\n\n<details><summary>Test Output</summary>\n\n```\n' + testOutput + '\n```\n</details>'
              });
            } catch (error) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '❌ **Tests failed to run.** There may be a configuration issue.\n\n```\n' + error.message + '\n```'
              });
            } 